trigger:
- task: Docker@2
  inputs:
    containerRegistry: 'java postgres'
    repository: 'javapostgres553587'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Docker@2
  inputs:
    containerRegistry: 'javapostgres553587'
    repository: 'postgres'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest

- task: Docker@2
  inputs:
    containerRegistry: 'javapostgres553587'
    repository: 'postgresql'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'